services:
  madr_db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  madr_app:
    image: madr_app
    build: .
    entrypoint: ./entrypoint.sh
    env_file: 
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - madr_db
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@madr_db:5432/${POSTGRES_DB}

volumes:
  pgdata: