"""add usuarios created_at and relationships

Revision ID: 517670aeb7cd
Revises: a1a1e358a60b
Create Date: 2024-11-03 15:57:17.774603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517670aeb7cd'
down_revision: Union[str, None] = 'a1a1e358a60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'livros', ['titulo'])
    op.create_unique_constraint(None, 'romancistas', ['nome'])
    op.add_column('usuarios', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'created_at')
    op.drop_constraint(None, 'romancistas', type_='unique')
    op.drop_constraint(None, 'livros', type_='unique')
    # ### end Alembic commands ###
